persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

listener 1883
allow_anonymous true

max_connections -1
max_inflight_messages 1000
max_queued_messages 100000
message_size_limit 0

queue_qos0_messages true

retain_available true

upgrade_outgoing_qos false

connection_messages true

keepalive_interval 60

persistence true
autosave_interval 300
autosave_on_changes true

allow_zero_length_clientid true
